#include "EcoPic.h"
#define TEXT_STAGE_WIDTH 128
#define TEXT_HEIGHT 64
#define TEXT_DIGIT_WIDTH 32

#define TEXT_SMALL_WIDTH 16
#define TEXT_SMALL_HEIGHT 16

#define CG_WIDTH 512
#define CG_HEIGHT 448